[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [build]
  command = "npm run build"  # Build command
  publish = "build"  # Directory to deploy

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200